<?xml version="1.0" encoding="utf-8"?><Database Name="Assignment" Class="DataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ASUSG51VX\ISNT;Initial Catalog=Assignment;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AssignmentConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblAccount" Member="tblAccounts">
    <Type Name="tblAccount">
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblCategory" Member="tblCategories">
    <Type Name="tblCategory">
      <Column Name="CategoryID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblComment" Member="tblComments">
    <Type Name="tblComment">
      <Column Name="FilmID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CommentID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CommentContent" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblFilm" Member="tblFilms">
    <Type Name="tblFilm">
      <Column Name="FilmID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CategoryID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ShortTitle" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FullTitle" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Poster" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LinkFilm" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>